name: Build Release App

on:
  workflow_dispatch
  # push:
  #   branches: 
  #   - master
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: Timestamp=`date '+%F_%H:%M:%S'`;rclone copyto $PWD/app/build/outputs/apk/release goorm-server:/var/www/html/My-PWA-App_$Timestamp
      env:
        RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}

    # - uses: actions/upload-artifact@v3
    #   with:
    #    name: Debug Application
    #    path: ./app/build/outputs/apk/debug/app-debug.apk
      
